apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: demo
  namespace: default
spec:
  activeCommitStatuses:
    # The ArgoCDCommitStatus CR will maintain this commit status based on the application health.
    - key: argocd-health
  environments:
  - autoMerge: false
    branch: environments/dev
  - autoMerge: false
    branch: environments/val
  - autoMerge: false
    branch: environments/prod
  gitRepositoryRef:
    name: yogeek-argocd-example-apps # The name of the GitRepository resource
